// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filekeytool

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileHandler creates a new instance of MockFileHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileHandler {
	mock := &MockFileHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileHandler is an autogenerated mock type for the FileHandler type
type MockFileHandler struct {
	mock.Mock
}

type MockFileHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileHandler) EXPECT() *MockFileHandler_Expecter {
	return &MockFileHandler_Expecter{mock: &_m.Mock}
}

// EnsureDirExists provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) EnsureDirExists(dirname string) error {
	ret := _mock.Called(dirname)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDirExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(dirname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileHandler_EnsureDirExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDirExists'
type MockFileHandler_EnsureDirExists_Call struct {
	*mock.Call
}

// EnsureDirExists is a helper method to define mock.On call
//   - dirname string
func (_e *MockFileHandler_Expecter) EnsureDirExists(dirname interface{}) *MockFileHandler_EnsureDirExists_Call {
	return &MockFileHandler_EnsureDirExists_Call{Call: _e.mock.On("EnsureDirExists", dirname)}
}

func (_c *MockFileHandler_EnsureDirExists_Call) Run(run func(dirname string)) *MockFileHandler_EnsureDirExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileHandler_EnsureDirExists_Call) Return(err error) *MockFileHandler_EnsureDirExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileHandler_EnsureDirExists_Call) RunAndReturn(run func(dirname string) error) *MockFileHandler_EnsureDirExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetCwd provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) GetCwd() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCwd")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileHandler_GetCwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCwd'
type MockFileHandler_GetCwd_Call struct {
	*mock.Call
}

// GetCwd is a helper method to define mock.On call
func (_e *MockFileHandler_Expecter) GetCwd() *MockFileHandler_GetCwd_Call {
	return &MockFileHandler_GetCwd_Call{Call: _e.mock.On("GetCwd")}
}

func (_c *MockFileHandler_GetCwd_Call) Run(run func()) *MockFileHandler_GetCwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileHandler_GetCwd_Call) Return(s string, err error) *MockFileHandler_GetCwd_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileHandler_GetCwd_Call) RunAndReturn(run func() (string, error)) *MockFileHandler_GetCwd_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) ReadFile(filename string) ([]byte, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileHandler_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileHandler_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - filename string
func (_e *MockFileHandler_Expecter) ReadFile(filename interface{}) *MockFileHandler_ReadFile_Call {
	return &MockFileHandler_ReadFile_Call{Call: _e.mock.On("ReadFile", filename)}
}

func (_c *MockFileHandler_ReadFile_Call) Run(run func(filename string)) *MockFileHandler_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileHandler_ReadFile_Call) Return(bytes []byte, err error) *MockFileHandler_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileHandler_ReadFile_Call) RunAndReturn(run func(filename string) ([]byte, error)) *MockFileHandler_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteJSON provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) WriteJSON(filenames string, objToWrite any) error {
	ret := _mock.Called(filenames, objToWrite)

	if len(ret) == 0 {
		panic("no return value specified for WriteJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(filenames, objToWrite)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileHandler_WriteJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteJSON'
type MockFileHandler_WriteJSON_Call struct {
	*mock.Call
}

// WriteJSON is a helper method to define mock.On call
//   - filenames string
//   - objToWrite any
func (_e *MockFileHandler_Expecter) WriteJSON(filenames interface{}, objToWrite interface{}) *MockFileHandler_WriteJSON_Call {
	return &MockFileHandler_WriteJSON_Call{Call: _e.mock.On("WriteJSON", filenames, objToWrite)}
}

func (_c *MockFileHandler_WriteJSON_Call) Run(run func(filenames string, objToWrite any)) *MockFileHandler_WriteJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_WriteJSON_Call) Return(err error) *MockFileHandler_WriteJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileHandler_WriteJSON_Call) RunAndReturn(run func(filenames string, objToWrite any) error) *MockFileHandler_WriteJSON_Call {
	_c.Call.Return(run)
	return _c
}

// WriteText provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) WriteText(filename string, txt string) error {
	ret := _mock.Called(filename, txt)

	if len(ret) == 0 {
		panic("no return value specified for WriteText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(filename, txt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileHandler_WriteText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteText'
type MockFileHandler_WriteText_Call struct {
	*mock.Call
}

// WriteText is a helper method to define mock.On call
//   - filename string
//   - txt string
func (_e *MockFileHandler_Expecter) WriteText(filename interface{}, txt interface{}) *MockFileHandler_WriteText_Call {
	return &MockFileHandler_WriteText_Call{Call: _e.mock.On("WriteText", filename, txt)}
}

func (_c *MockFileHandler_WriteText_Call) Run(run func(filename string, txt string)) *MockFileHandler_WriteText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_WriteText_Call) Return(err error) *MockFileHandler_WriteText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileHandler_WriteText_Call) RunAndReturn(run func(filename string, txt string) error) *MockFileHandler_WriteText_Call {
	_c.Call.Return(run)
	return _c
}
