// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package certificate

import (
	"github.com/mathworks/mjssetup/pkg/certificate"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreator creates a new instance of MockCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreator {
	mock := &MockCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreator is an autogenerated mock type for the Creator type
type MockCreator struct {
	mock.Mock
}

type MockCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreator) EXPECT() *MockCreator_Expecter {
	return &MockCreator_Expecter{mock: &_m.Mock}
}

// CreateSharedSecret provides a mock function for the type MockCreator
func (_mock *MockCreator) CreateSharedSecret() (*certificate.SharedSecret, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateSharedSecret")
	}

	var r0 *certificate.SharedSecret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*certificate.SharedSecret, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *certificate.SharedSecret); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.SharedSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_CreateSharedSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSharedSecret'
type MockCreator_CreateSharedSecret_Call struct {
	*mock.Call
}

// CreateSharedSecret is a helper method to define mock.On call
func (_e *MockCreator_Expecter) CreateSharedSecret() *MockCreator_CreateSharedSecret_Call {
	return &MockCreator_CreateSharedSecret_Call{Call: _e.mock.On("CreateSharedSecret")}
}

func (_c *MockCreator_CreateSharedSecret_Call) Run(run func()) *MockCreator_CreateSharedSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCreator_CreateSharedSecret_Call) Return(sharedSecret *certificate.SharedSecret, err error) *MockCreator_CreateSharedSecret_Call {
	_c.Call.Return(sharedSecret, err)
	return _c
}

func (_c *MockCreator_CreateSharedSecret_Call) RunAndReturn(run func() (*certificate.SharedSecret, error)) *MockCreator_CreateSharedSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCertificate provides a mock function for the type MockCreator
func (_mock *MockCreator) GenerateCertificate(sharedSecret *certificate.SharedSecret) (*certificate.Certificate, error) {
	ret := _mock.Called(sharedSecret)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCertificate")
	}

	var r0 *certificate.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret) (*certificate.Certificate, error)); ok {
		return returnFunc(sharedSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret) *certificate.Certificate); ok {
		r0 = returnFunc(sharedSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*certificate.SharedSecret) error); ok {
		r1 = returnFunc(sharedSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_GenerateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCertificate'
type MockCreator_GenerateCertificate_Call struct {
	*mock.Call
}

// GenerateCertificate is a helper method to define mock.On call
//   - sharedSecret *certificate.SharedSecret
func (_e *MockCreator_Expecter) GenerateCertificate(sharedSecret interface{}) *MockCreator_GenerateCertificate_Call {
	return &MockCreator_GenerateCertificate_Call{Call: _e.mock.On("GenerateCertificate", sharedSecret)}
}

func (_c *MockCreator_GenerateCertificate_Call) Run(run func(sharedSecret *certificate.SharedSecret)) *MockCreator_GenerateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *certificate.SharedSecret
		if args[0] != nil {
			arg0 = args[0].(*certificate.SharedSecret)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreator_GenerateCertificate_Call) Return(certificate1 *certificate.Certificate, err error) *MockCreator_GenerateCertificate_Call {
	_c.Call.Return(certificate1, err)
	return _c
}

func (_c *MockCreator_GenerateCertificate_Call) RunAndReturn(run func(sharedSecret *certificate.SharedSecret) (*certificate.Certificate, error)) *MockCreator_GenerateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCertificateWithHostname provides a mock function for the type MockCreator
func (_mock *MockCreator) GenerateCertificateWithHostname(sharedSecret *certificate.SharedSecret, s string) (*certificate.Certificate, error) {
	ret := _mock.Called(sharedSecret, s)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCertificateWithHostname")
	}

	var r0 *certificate.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret, string) (*certificate.Certificate, error)); ok {
		return returnFunc(sharedSecret, s)
	}
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret, string) *certificate.Certificate); ok {
		r0 = returnFunc(sharedSecret, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*certificate.SharedSecret, string) error); ok {
		r1 = returnFunc(sharedSecret, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_GenerateCertificateWithHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCertificateWithHostname'
type MockCreator_GenerateCertificateWithHostname_Call struct {
	*mock.Call
}

// GenerateCertificateWithHostname is a helper method to define mock.On call
//   - sharedSecret *certificate.SharedSecret
//   - s string
func (_e *MockCreator_Expecter) GenerateCertificateWithHostname(sharedSecret interface{}, s interface{}) *MockCreator_GenerateCertificateWithHostname_Call {
	return &MockCreator_GenerateCertificateWithHostname_Call{Call: _e.mock.On("GenerateCertificateWithHostname", sharedSecret, s)}
}

func (_c *MockCreator_GenerateCertificateWithHostname_Call) Run(run func(sharedSecret *certificate.SharedSecret, s string)) *MockCreator_GenerateCertificateWithHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *certificate.SharedSecret
		if args[0] != nil {
			arg0 = args[0].(*certificate.SharedSecret)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreator_GenerateCertificateWithHostname_Call) Return(certificate1 *certificate.Certificate, err error) *MockCreator_GenerateCertificateWithHostname_Call {
	_c.Call.Return(certificate1, err)
	return _c
}

func (_c *MockCreator_GenerateCertificateWithHostname_Call) RunAndReturn(run func(sharedSecret *certificate.SharedSecret, s string) (*certificate.Certificate, error)) *MockCreator_GenerateCertificateWithHostname_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCertificate provides a mock function for the type MockCreator
func (_mock *MockCreator) LoadCertificate(bytes []byte) (*certificate.Certificate, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for LoadCertificate")
	}

	var r0 *certificate.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*certificate.Certificate, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *certificate.Certificate); ok {
		r0 = returnFunc(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_LoadCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCertificate'
type MockCreator_LoadCertificate_Call struct {
	*mock.Call
}

// LoadCertificate is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockCreator_Expecter) LoadCertificate(bytes interface{}) *MockCreator_LoadCertificate_Call {
	return &MockCreator_LoadCertificate_Call{Call: _e.mock.On("LoadCertificate", bytes)}
}

func (_c *MockCreator_LoadCertificate_Call) Run(run func(bytes []byte)) *MockCreator_LoadCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreator_LoadCertificate_Call) Return(certificate1 *certificate.Certificate, err error) *MockCreator_LoadCertificate_Call {
	_c.Call.Return(certificate1, err)
	return _c
}

func (_c *MockCreator_LoadCertificate_Call) RunAndReturn(run func(bytes []byte) (*certificate.Certificate, error)) *MockCreator_LoadCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSharedSecret provides a mock function for the type MockCreator
func (_mock *MockCreator) LoadSharedSecret(bytes []byte) (*certificate.SharedSecret, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for LoadSharedSecret")
	}

	var r0 *certificate.SharedSecret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*certificate.SharedSecret, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *certificate.SharedSecret); ok {
		r0 = returnFunc(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.SharedSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_LoadSharedSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSharedSecret'
type MockCreator_LoadSharedSecret_Call struct {
	*mock.Call
}

// LoadSharedSecret is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockCreator_Expecter) LoadSharedSecret(bytes interface{}) *MockCreator_LoadSharedSecret_Call {
	return &MockCreator_LoadSharedSecret_Call{Call: _e.mock.On("LoadSharedSecret", bytes)}
}

func (_c *MockCreator_LoadSharedSecret_Call) Run(run func(bytes []byte)) *MockCreator_LoadSharedSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreator_LoadSharedSecret_Call) Return(sharedSecret *certificate.SharedSecret, err error) *MockCreator_LoadSharedSecret_Call {
	_c.Call.Return(sharedSecret, err)
	return _c
}

func (_c *MockCreator_LoadSharedSecret_Call) RunAndReturn(run func(bytes []byte) (*certificate.SharedSecret, error)) *MockCreator_LoadSharedSecret_Call {
	_c.Call.Return(run)
	return _c
}
