// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package keytool

import (
	"github.com/mathworks/mjssetup/internal/keytool"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeytool creates a new instance of MockKeytool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeytool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeytool {
	mock := &MockKeytool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeytool is an autogenerated mock type for the Keytool type
type MockKeytool struct {
	mock.Mock
}

type MockKeytool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeytool) EXPECT() *MockKeytool_Expecter {
	return &MockKeytool_Expecter{mock: &_m.Mock}
}

// CreateProfile provides a mock function for the type MockKeytool
func (_mock *MockKeytool) CreateProfile(inputs *keytool.CreateProfileInputs) error {
	ret := _mock.Called(inputs)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*keytool.CreateProfileInputs) error); ok {
		r0 = returnFunc(inputs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeytool_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type MockKeytool_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - inputs *keytool.CreateProfileInputs
func (_e *MockKeytool_Expecter) CreateProfile(inputs interface{}) *MockKeytool_CreateProfile_Call {
	return &MockKeytool_CreateProfile_Call{Call: _e.mock.On("CreateProfile", inputs)}
}

func (_c *MockKeytool_CreateProfile_Call) Run(run func(inputs *keytool.CreateProfileInputs)) *MockKeytool_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *keytool.CreateProfileInputs
		if args[0] != nil {
			arg0 = args[0].(*keytool.CreateProfileInputs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeytool_CreateProfile_Call) Return(err error) *MockKeytool_CreateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeytool_CreateProfile_Call) RunAndReturn(run func(inputs *keytool.CreateProfileInputs) error) *MockKeytool_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSharedSecret provides a mock function for the type MockKeytool
func (_mock *MockKeytool) CreateSharedSecret(inputs *keytool.CreateSharedSecretInputs) error {
	ret := _mock.Called(inputs)

	if len(ret) == 0 {
		panic("no return value specified for CreateSharedSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*keytool.CreateSharedSecretInputs) error); ok {
		r0 = returnFunc(inputs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeytool_CreateSharedSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSharedSecret'
type MockKeytool_CreateSharedSecret_Call struct {
	*mock.Call
}

// CreateSharedSecret is a helper method to define mock.On call
//   - inputs *keytool.CreateSharedSecretInputs
func (_e *MockKeytool_Expecter) CreateSharedSecret(inputs interface{}) *MockKeytool_CreateSharedSecret_Call {
	return &MockKeytool_CreateSharedSecret_Call{Call: _e.mock.On("CreateSharedSecret", inputs)}
}

func (_c *MockKeytool_CreateSharedSecret_Call) Run(run func(inputs *keytool.CreateSharedSecretInputs)) *MockKeytool_CreateSharedSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *keytool.CreateSharedSecretInputs
		if args[0] != nil {
			arg0 = args[0].(*keytool.CreateSharedSecretInputs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeytool_CreateSharedSecret_Call) Return(err error) *MockKeytool_CreateSharedSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeytool_CreateSharedSecret_Call) RunAndReturn(run func(inputs *keytool.CreateSharedSecretInputs) error) *MockKeytool_CreateSharedSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCertificate provides a mock function for the type MockKeytool
func (_mock *MockKeytool) GenerateCertificate(inputs *keytool.GenerateCertificateInputs) error {
	ret := _mock.Called(inputs)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCertificate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*keytool.GenerateCertificateInputs) error); ok {
		r0 = returnFunc(inputs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeytool_GenerateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCertificate'
type MockKeytool_GenerateCertificate_Call struct {
	*mock.Call
}

// GenerateCertificate is a helper method to define mock.On call
//   - inputs *keytool.GenerateCertificateInputs
func (_e *MockKeytool_Expecter) GenerateCertificate(inputs interface{}) *MockKeytool_GenerateCertificate_Call {
	return &MockKeytool_GenerateCertificate_Call{Call: _e.mock.On("GenerateCertificate", inputs)}
}

func (_c *MockKeytool_GenerateCertificate_Call) Run(run func(inputs *keytool.GenerateCertificateInputs)) *MockKeytool_GenerateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *keytool.GenerateCertificateInputs
		if args[0] != nil {
			arg0 = args[0].(*keytool.GenerateCertificateInputs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeytool_GenerateCertificate_Call) Return(err error) *MockKeytool_GenerateCertificate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeytool_GenerateCertificate_Call) RunAndReturn(run func(inputs *keytool.GenerateCertificateInputs) error) *MockKeytool_GenerateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateMetricsCertificatesAndKeys provides a mock function for the type MockKeytool
func (_mock *MockKeytool) GenerateMetricsCertificatesAndKeys(inputs *keytool.GenerateMetricsCertificatesAndKeysInputs) error {
	ret := _mock.Called(inputs)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMetricsCertificatesAndKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*keytool.GenerateMetricsCertificatesAndKeysInputs) error); ok {
		r0 = returnFunc(inputs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeytool_GenerateMetricsCertificatesAndKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMetricsCertificatesAndKeys'
type MockKeytool_GenerateMetricsCertificatesAndKeys_Call struct {
	*mock.Call
}

// GenerateMetricsCertificatesAndKeys is a helper method to define mock.On call
//   - inputs *keytool.GenerateMetricsCertificatesAndKeysInputs
func (_e *MockKeytool_Expecter) GenerateMetricsCertificatesAndKeys(inputs interface{}) *MockKeytool_GenerateMetricsCertificatesAndKeys_Call {
	return &MockKeytool_GenerateMetricsCertificatesAndKeys_Call{Call: _e.mock.On("GenerateMetricsCertificatesAndKeys", inputs)}
}

func (_c *MockKeytool_GenerateMetricsCertificatesAndKeys_Call) Run(run func(inputs *keytool.GenerateMetricsCertificatesAndKeysInputs)) *MockKeytool_GenerateMetricsCertificatesAndKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *keytool.GenerateMetricsCertificatesAndKeysInputs
		if args[0] != nil {
			arg0 = args[0].(*keytool.GenerateMetricsCertificatesAndKeysInputs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeytool_GenerateMetricsCertificatesAndKeys_Call) Return(err error) *MockKeytool_GenerateMetricsCertificatesAndKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeytool_GenerateMetricsCertificatesAndKeys_Call) RunAndReturn(run func(inputs *keytool.GenerateMetricsCertificatesAndKeysInputs) error) *MockKeytool_GenerateMetricsCertificatesAndKeys_Call {
	_c.Call.Return(run)
	return _c
}
